export const GalleryHeader = () => {
  return (
    <header className="items-center box-border caret-transparent flex flex-col text-center mb-6">
      <p className="text-gray-300 box-border caret-transparent w-auto md:w-[33.3333%]">
        Explore over 20 million AI Girl Images and Prompts generated by the
        community.
      </p>
    </header>
  );
};
